import type { BrandItem } from './types'

/** Additional BrandItems merged into catalog; seed rows can be patched via variantId here. */
export const BRAND_EXTENSIONS: BrandItem[] = [
  {
    id: 'brand_wu_tao_chicken_leg_rice',
    brandName: '悟饕',
    itemName: '雞腿飯',
    templateId: 'dish_chicken_leg_rice',
    variantId: 'variant_braised_chicken_leg_rice',
    calories: 850,
    protein: 38,
    fat: 32,
    carbs: 95,
    sourceType: 'database_estimate',
    confidence: 'medium',
    aliases: ['悟饕雞腿飯', '悟饕雞腿便當', '悟饕滷雞腿飯'],
    tags: ['便當', '雞腿飯', '滷'],
    note: '估算偏滷',
  },
  {
    id: 'brand_chishang_chicken_leg_bento',
    brandName: '池上',
    itemName: '雞腿便當',
    templateId: 'dish_chicken_leg_rice',
    variantId: 'variant_braised_chicken_leg_rice',
    calories: 820,
    protein: 36,
    fat: 30,
    carbs: 95,
    sourceType: 'database_estimate',
    confidence: 'medium',
    aliases: ['池上雞腿飯', '池上雞腿便當'],
    tags: ['便當', '雞腿飯', '滷'],
    note: '估算偏滷',
  },
  {
    id: 'brand_chicken_king_chicken_leg_rice',
    brandName: '雞腿王',
    itemName: '炸雞腿飯',
    templateId: 'dish_chicken_leg_rice',
    variantId: 'variant_fried_chicken_leg_rice',
    calories: 900,
    protein: 40,
    fat: 35,
    carbs: 100,
    sourceType: 'database_estimate',
    confidence: 'medium',
    aliases: ['雞腿王雞腿飯', '雞腿王炸雞腿飯', '雞腿王雞腿便當'],
    tags: ['便當', '雞腿飯', '炸'],
  },
  {
    id: 'brand_sunright_grilled_chicken',
    brandName: '三商巧福',
    itemName: '烤雞腿飯',
    templateId: 'dish_chicken_leg_rice',
    variantId: 'variant_grilled_chicken_leg_rice',
    calories: 820,
    protein: 38,
    fat: 28,
    carbs: 92,
    sourceType: 'database_estimate',
    confidence: 'medium',
    aliases: ['三商烤雞腿飯', '三商巧福烤雞腿飯'],
    tags: ['便當', '雞腿飯', '烤'],
  },
  {
    id: 'brand_wu_tao_braised_chicken',
    brandName: '悟饕',
    itemName: '滷雞腿飯',
    templateId: 'dish_chicken_leg_rice',
    variantId: 'variant_braised_chicken_leg_rice',
    calories: 850,
    protein: 38,
    fat: 32,
    carbs: 95,
    sourceType: 'database_estimate',
    confidence: 'medium',
    aliases: ['悟饕滷雞腿飯'],
    tags: ['便當', '雞腿飯', '滷'],
  },
]

export const BRAND_EXTENSION_IDS = new Set(BRAND_EXTENSIONS.map(b => b.id))
