/** Auto-generated by scripts/build-top300-allowlist.mjs — do not edit manually */
import data from '../../../data/food-kb/food-source-allowlist.json'

export interface FoodSourceAllowlistEntry {
  rank: number
  input_name: string
  canonical_name: string
  source_type: string
  menu_clusters: string[]
  search_aliases: string[]
  confidence_level: 'A' | 'B'
  quarantine_exempt: true
  seed_priority: 'P0' | 'P1'
  needs_cross_validation: boolean
  slug: string
}

export interface FoodSourceAllowlist {
  version: string
  generated_at: string
  count: number
  p0_count: number
  p1_count: number
  unique_canonical: number
  policy: 'quarantine_exempt'
  entries: FoodSourceAllowlistEntry[]
  index: Record<string, string>
}

export const FOOD_SOURCE_ALLOWLIST = data as FoodSourceAllowlist
/** @deprecated use FOOD_SOURCE_ALLOWLIST */
export const TOP300_ALLOWLIST = FOOD_SOURCE_ALLOWLIST

export type Top300AllowlistEntry = FoodSourceAllowlistEntry
export type Top300Allowlist = FoodSourceAllowlist

export function isQuarantineExempt(name: string): boolean {
  const key = name.trim().toLowerCase().replace(/\s+/g, '')
  return Boolean(FOOD_SOURCE_ALLOWLIST.index[key])
}

export function resolveCanonicalAllowlist(name: string): FoodSourceAllowlistEntry | null {
  const key = name.trim().toLowerCase().replace(/\s+/g, '')
  const canonical = FOOD_SOURCE_ALLOWLIST.index[key]
  if (!canonical) return null
  return FOOD_SOURCE_ALLOWLIST.entries.find(e => e.canonical_name === canonical) ?? null
}

export function needsCrossValidation(name: string): boolean {
  const entry = resolveCanonicalAllowlist(name)
  return entry?.needs_cross_validation === true
}

export function allAllowlistCanonicalNames(): string[] {
  return [...new Set(FOOD_SOURCE_ALLOWLIST.entries.map(e => e.canonical_name))]
}

export function p1SeedEntries(): FoodSourceAllowlistEntry[] {
  return FOOD_SOURCE_ALLOWLIST.entries.filter(e => e.seed_priority === 'P1')
}
