import type { BrandCatalog } from './helpers'
import { drink, meal, side } from './helpers'

/** 五十嵐、清心、CoCo… — 每品牌獨立單點品項 */
export const BUBBLETEA_CATALOG: BrandCatalog = {
  '50lan': [
    drink({ name: '珍珠奶茶（大杯）', calories: 668, protein_g: 1, carbs_g: 68, price: 55, sugar_g: 53, aliases: ['大杯珍奶', '奶茶', '大冰奶'], tags: ['bubble_tea'] }),
    drink({ name: '波霸奶茶（大杯）', calories: 678, protein_g: 1, carbs_g: 70, price: 55, sugar_g: 53, tags: ['bubble_tea'] }),
    drink({ name: '燕麥奶茶（大杯）', calories: 472, protein_g: 1, carbs_g: 62, price: 60, sugar_g: 45, tags: ['bubble_tea'] }),
    drink({ name: '奶綠（大杯）', calories: 532, protein_g: 1, carbs_g: 58, price: 50, sugar_g: 46, aliases: ['奶茶綠'], tags: ['bubble_tea'] }),
    drink({ name: '四季春青茶（中杯）', calories: 119, protein_g: 1, carbs_g: 28, price: 30, sugar_g: 28, aliases: ['四季春', '青茶'], tags: ['bubble_tea'] }),
    drink({ name: '烏龍綠茶（中杯）', calories: 119, protein_g: 1, carbs_g: 28, price: 30, sugar_g: 28, tags: ['bubble_tea'] }),
    drink({ name: '8冰茶（大杯）', calories: 291, protein_g: 1, carbs_g: 72, price: 45, sugar_g: 67, tags: ['bubble_tea'] }),
    drink({ name: '檸檬綠茶（大杯）', calories: 217, protein_g: 1, carbs_g: 54, price: 50, sugar_g: 48, tags: ['bubble_tea'] }),
    drink({ name: '蜂蜜綠茶（大杯）', calories: 250, protein_g: 1, carbs_g: 62, price: 50, sugar_g: 55, tags: ['bubble_tea'] }),
    drink({ name: '芒果青茶（大杯）', calories: 319, protein_g: 1, carbs_g: 78, price: 55, sugar_g: 70, tags: ['bubble_tea'] }),
    drink({ name: '冰淇淋紅茶（大杯）', calories: 436, protein_g: 1, carbs_g: 82, price: 65, sugar_g: 67, tags: ['bubble_tea'] }),
    drink({ name: '阿華田（中杯）', calories: 359, protein_g: 1, carbs_g: 48, price: 55, sugar_g: 33, tags: ['bubble_tea'] }),
  ],
  'ching-shin': [
    drink({ name: '珍珠奶茶（大杯）', calories: 720, protein_g: 1, carbs_g: 66, price: 50, sugar_g: 52, aliases: ['珍奶'], tags: ['bubble_tea'] }),
    drink({ name: '波霸奶茶（大杯）', calories: 425, protein_g: 1, carbs_g: 68, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '奶綠（大杯）', calories: 370, protein_g: 1, carbs_g: 56, price: 48, tags: ['bubble_tea'] }),
    drink({ name: '烏龍奶茶（大杯）', calories: 390, protein_g: 1, carbs_g: 60, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '四季春茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 25, tags: ['bubble_tea'] }),
    drink({ name: '檸檬汁（中杯）', calories: 120, protein_g: 1, carbs_g: 30, price: 45, tags: ['bubble_tea'] }),
    drink({ name: '金桔檸檬（大杯）', calories: 200, protein_g: 1, carbs_g: 50, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '仙草凍奶茶（大杯）', calories: 350, protein_g: 1, carbs_g: 58, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '布丁奶茶（大杯）', calories: 400, protein_g: 1, carbs_g: 62, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '蜂蜜奶茶（大杯）', calories: 380, protein_g: 1, carbs_g: 60, price: 52, tags: ['bubble_tea'] }),
  ],
  'coco-tea': [
    drink({ name: '珍珠奶茶（大杯）', calories: 415, protein_g: 1, carbs_g: 67, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '百香雙響炮（大杯）', calories: 280, protein_g: 1, carbs_g: 68, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '奶茶三兄弟（大杯）', calories: 450, protein_g: 1, carbs_g: 72, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '鮮芋青稞牛奶（大杯）', calories: 380, protein_g: 1, carbs_g: 55, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '綠茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 25, tags: ['bubble_tea'] }),
    drink({ name: '檸檬霸（大杯）', calories: 190, protein_g: 1, carbs_g: 48, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '巧克力奶茶（大杯）', calories: 420, protein_g: 1, carbs_g: 65, price: 58, tags: ['bubble_tea'] }),
    drink({ name: '芒果冰沙（大杯）', calories: 320, protein_g: 1, carbs_g: 78, price: 70, tags: ['bubble_tea'] }),
    drink({ name: '芋頭牛奶（大杯）', calories: 360, protein_g: 1, carbs_g: 52, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '鮮奶茶（中杯·微糖）', calories: 220, protein_g: 1, carbs_g: 32, price: 48, aliases: ['鮮奶綠'], tags: ['bubble_tea'] }),
  ],
  'kebu-ke': [
    drink({ name: '熟成紅茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 30, tags: ['bubble_tea'] }),
    drink({ name: '熟成紅茶拿鐵（大杯）', calories: 280, protein_g: 1, carbs_g: 38, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '珍珠奶茶（大杯）', calories: 400, protein_g: 1, carbs_g: 64, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '珍珠鮮奶茶（大杯）', calories: 350, protein_g: 1, carbs_g: 48, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '珍珠烏龍奶（大杯）', calories: 380, protein_g: 1, carbs_g: 58, price: 58, tags: ['bubble_tea'] }),
    drink({ name: '珍珠紅茶拿鐵（大杯）', calories: 300, protein_g: 1, carbs_g: 42, price: 62, tags: ['bubble_tea'] }),
    drink({ name: '珍珠紅茶拿鐵（中杯）', calories: 220, protein_g: 1, carbs_g: 30, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '珍珠紅（大杯）', calories: 250, protein_g: 1, carbs_g: 62, price: 50, tags: ['bubble_tea'] }),
  ],
  'milkshop': [
    drink({ name: '珍珠鮮奶（大杯）', calories: 380, protein_g: 1, carbs_g: 45, price: 70, tags: ['bubble_tea'] }),
    drink({ name: '紅茶拿鐵（大杯）', calories: 290, protein_g: 1, carbs_g: 40, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '綠茶拿鐵（大杯）', calories: 285, protein_g: 1, carbs_g: 38, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '珍珠紅茶（大杯）', calories: 350, protein_g: 1, carbs_g: 58, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '珍珠綠茶（大杯）', calories: 340, protein_g: 1, carbs_g: 55, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '鮮奶綠（大杯）', calories: 320, protein_g: 1, carbs_g: 42, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '芋頭鮮奶（大杯）', calories: 360, protein_g: 1, carbs_g: 48, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '黑糖鮮奶（大杯）', calories: 400, protein_g: 1, carbs_g: 50, price: 70, tags: ['bubble_tea'] }),
  ],
  'mago': [
    drink({ name: '芝芝葡萄（大杯）', calories: 320, protein_g: 1, carbs_g: 72, price: 75, tags: ['bubble_tea'] }),
    drink({ name: '芝芝芒果（大杯）', calories: 340, protein_g: 1, carbs_g: 78, price: 75, tags: ['bubble_tea'] }),
    drink({ name: '楊枝甘露（大杯）', calories: 380, protein_g: 1, carbs_g: 82, price: 80, tags: ['bubble_tea'] }),
    drink({ name: '珍珠奶茶（大杯）', calories: 410, protein_g: 1, carbs_g: 66, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '葡萄柚綠茶（大杯）', calories: 200, protein_g: 1, carbs_g: 50, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '檸檬汁（大杯）', calories: 150, protein_g: 1, carbs_g: 38, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '燕麥奶茶（大杯）', calories: 390, protein_g: 1, carbs_g: 60, price: 58, tags: ['bubble_tea'] }),
  ],
  'dayung': [
    drink({ name: '翡翠檸檬（大杯）', calories: 180, protein_g: 1, carbs_g: 45, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '百香雙Q（大杯）', calories: 290, protein_g: 1, carbs_g: 70, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '珍珠奶茶（大杯）', calories: 405, protein_g: 1, carbs_g: 65, price: 52, tags: ['bubble_tea'] }),
    drink({ name: '芋頭牛奶（大杯）', calories: 370, protein_g: 1, carbs_g: 55, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '鮮奶茶（大杯）', calories: 340, protein_g: 1, carbs_g: 48, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '四季春茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 28, tags: ['bubble_tea'] }),
  ],
  'tea-top': [
    drink({ name: '黃金烏龍（中杯）', calories: 8, protein_g: 1, carbs_g: 2, price: 30, tags: ['bubble_tea'] }),
    drink({ name: '珍珠奶茶（大杯）', calories: 400, protein_g: 1, carbs_g: 64, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '鐵觀音奶茶（大杯）', calories: 390, protein_g: 1, carbs_g: 62, price: 52, tags: ['bubble_tea'] }),
    drink({ name: '紅茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 25, tags: ['bubble_tea'] }),
    drink({ name: '冬瓜檸檬（大杯）', calories: 160, protein_g: 1, carbs_g: 40, price: 45, tags: ['bubble_tea'] }),
    drink({ name: '仙草凍奶（大杯）', calories: 320, protein_g: 1, carbs_g: 50, price: 55, tags: ['bubble_tea'] }),
  ],
  'woolong': [
    drink({ name: '烏龍綠茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 28, tags: ['bubble_tea'] }),
    drink({ name: '珍珠奶茶（大杯）', calories: 395, protein_g: 1, carbs_g: 63, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '紅茶拿鐵（大杯）', calories: 280, protein_g: 1, carbs_g: 38, price: 60, tags: ['bubble_tea'] }),
    drink({ name: '檸檬烏龍（大杯）', calories: 170, protein_g: 1, carbs_g: 42, price: 52, tags: ['bubble_tea'] }),
    drink({ name: '多多綠（大杯）', calories: 200, protein_g: 1, carbs_g: 48, price: 55, tags: ['bubble_tea'] }),
  ],
  'yimu': [
    drink({ name: '黃金蕎麥（中杯）', calories: 10, protein_g: 1, carbs_g: 2, price: 45, tags: ['bubble_tea'] }),
    drink({ name: '桂花蕎麥（中杯）', calories: 15, protein_g: 1, carbs_g: 3, price: 48, tags: ['bubble_tea'] }),
    drink({ name: '檸檬蕎麥（中杯）', calories: 80, protein_g: 1, carbs_g: 20, price: 50, tags: ['bubble_tea'] }),
    drink({ name: '奶茶（大杯）', calories: 380, protein_g: 1, carbs_g: 58, price: 55, tags: ['bubble_tea'] }),
    drink({ name: '紅茶（中杯）', calories: 5, protein_g: 1, carbs_g: 1, price: 35, tags: ['bubble_tea'] }),
  ],
  'nap-5min': [
    drink({ name: '珍珠奶茶（大杯）', calories: 410, protein_g: 1, carbs_g: 66, price: 65, tags: ['bubble_tea'] }),
    drink({ name: '紅茶拿鐵（大杯）', calories: 300, protein_g: 1, carbs_g: 42, price: 70, tags: ['bubble_tea'] }),
    drink({ name: '綠茶拿鐵（大杯）', calories: 295, protein_g: 1, carbs_g: 40, price: 70, tags: ['bubble_tea'] }),
    drink({ name: '可可芭蕾（大杯）', calories: 380, protein_g: 1, carbs_g: 58, price: 72, tags: ['bubble_tea'] }),
    drink({ name: '焙茶拿鐵（大杯）', calories: 290, protein_g: 1, carbs_g: 38, price: 72, tags: ['bubble_tea'] }),
  ],
}
