import type { RecommendationQaReport } from './types'

export function formatRecommendationQaMarkdown(report: RecommendationQaReport): string {
  const lines: string[] = [
    '# BetterBit Recommendation QA Report',
    '',
    `Generated: ${report.generated_at}`,
    '',
    '> **Offline QA only** — does not modify Production or runtime database.',
    '> Awaiting Founder approval before any data or recommendation policy changes.',
    '',
    '## Executive Summary',
    '',
    '| Dimension | Result |',
    '|-----------|--------|',
    `| Restaurant coverage (600 allowlist) | ${report.restaurant_coverage.with_menu}/${report.restaurant_coverage.allowlist_total} (${report.restaurant_coverage.coverage_pct}%) |`,
    `| Menu items audited (${report.menu_scope}) | ${report.menu_coverage.items_audited} |`,
    `| Recommendable items (confidence A/B) | ${report.menu_coverage.items_recommendable} |`,
    `| Nutrition outliers | ${report.nutrition_outliers} |`,
    `| Placeholder / template menus | ${report.menu_coverage.placeholder_count} |`,
    `| Recommendation sample pass rate | ${report.recommendation_samples.pass_rate_pct}% |`,
    `| Explainability pass rate | ${report.recommendation_samples.explainability_pass_pct}% |`,
    '',
    '## ① Restaurant Exists',
    '',
    `- Allowlist restaurants: **${report.restaurant_coverage.allowlist_total}**`,
    `- With at least one menu item: **${report.restaurant_coverage.with_menu}**`,
    `- Without menu: **${report.restaurant_coverage.without_menu}**`,
    '',
    'Proxy: allowlist + registry match (offline). Live Google Maps / Uber Eats verification is a separate pipeline step.',
    '',
    '## ② Menu Exists',
    '',
    `- Items audited: ${report.menu_coverage.items_audited}`,
    `- Placeholder/template flagged: ${report.menu_coverage.placeholder_count}`,
    `- Incomplete nutrition: ${report.menu_coverage.incomplete_nutrition}`,
    '',
    '## ③ Nutrition Validation',
    '',
    '| Field | Coverage / Pass |',
    '|-------|-----------------|',
    `| Calories complete | ${report.macro_fields.calories_complete_pct}% |`,
    `| Protein complete | ${report.macro_fields.protein_complete_pct}% |`,
    `| Fat complete | ${report.macro_fields.fat_complete_pct}% |`,
    `| Carbs complete | ${report.macro_fields.carbs_complete_pct}% |`,
    `| Fiber | ${report.macro_fields.fiber_coverage_pct}% (not in core menu schema) |`,
    `| Sugar | ${report.macro_fields.sugar_coverage_pct}% (not in core menu schema) |`,
    `| Sodium | ${report.macro_fields.sodium_coverage_pct}% (not in core menu schema) |`,
    `| Energy balance (4P+4C+9F) | ${report.accuracy.energy_balance_pass_pct}% |`,
    '',
    'Source priority: official > USDA/TFDA > brand public > Food DNA > estimated pending. No averaging across tiers.',
    '',
    '## ④ Portion Validation',
    '',
    `Portion/macro plausibility pass: **${report.accuracy.portion_plausible_pct}%**`,
    '',
    '## ⑤ Macro Validation',
    '',
    `Within dish-type bands: **${report.accuracy.macro_in_range_pct}%**`,
    `Nutrition outliers flagged: **${report.nutrition_outliers}**`,
    '',
    '## ⑥ Recommendation Validation',
    '',
    `Scenarios sampled: ${report.recommendation_samples.scenarios_run}`,
    `Pass rate: ${report.recommendation_samples.pass_rate_pct}%`,
    `Confidence A/B: ${report.recommendation_samples.confidence_ab_pct}%`,
    '',
    '### Sample results',
    '',
    ...report.recommendation_results.map(r =>
      [
        `### ${r.scenario} (${r.meal_type})`,
        `- Valid: ${r.valid ? '✅' : '❌'}`,
        `- Confidence: **${r.confidence}**`,
        `- Recommendable: ${r.recommendable ? 'yes' : 'no'}`,
        `- Explainability: ${r.explainability_ok ? '✅' : '❌'}`,
        r.explanation ? `- Why: ${r.explanation}` : '',
        r.issues.length ? `- Issues: ${r.issues.join('; ')}` : '- Issues: none',
        '',
      ].join('\n')
    ),
    '',
    '## ⑦ Diet / Nutrition / Restaurant Scores',
    '',
    'Per-item scores recalculated fresh via `calculateDietScore` + `computeBetterBitFoodScore` (see JSON sample).',
    '',
    '## ⑧ Recommendation Confidence',
    '',
    '| Grade | Count | Policy |',
    '|-------|-------|--------|',
    `| A | ${report.confidence_distribution.A} | Normal recommend |`,
    `| B | ${report.confidence_distribution.B} | Normal recommend |`,
    `| C | ${report.confidence_distribution.C} | Recommend with caution |`,
    `| D | ${report.confidence_distribution.D} | Do not recommend |`,
    '',
    '## ⑨ Explainability',
    '',
    `Sample explainability pass: ${report.recommendation_samples.explainability_pass_pct}%`,
    '',
    '## ⑩ Top Gaps',
    '',
    '### Top missing menus (allowlist, no items)',
    '',
    ...(report.top_missing_menus.length
      ? report.top_missing_menus.map(s => `- ${s}`)
      : ['- _None_']),
    '',
    '### Top nutrition outliers',
    '',
    ...(report.top_outliers.length
      ? report.top_outliers.map(o => `- \`${o.id}\` @ ${o.store} — ${o.name}: ${o.issues.join('; ')}`)
      : ['- _None in sample_']),
    '',
    '---',
    '',
    '**Status: QA complete — awaiting Founder approval before production changes.**',
  ]

  return lines.join('\n')
}
