// 便利店菜單資料庫 - 7-11 & 全家 (完整真實菜單)
// 包含478個爬取產品中精選的最佳餐點

export interface ConvenienceItem {
  id: string
  name: string
  store: '7-11' | '全家'
  category: 'breakfast' | 'lunch' | 'dinner'
  calories: number
  protein_g: number
  carbs_g: number
  fat_g: number
  price: number
  photo_url: string
  description: string
}

export const convenienceStoreMenu: ConvenienceItem[] = [
  {
    "id": "7-11-lunch-1",
    "name": "泰式酸辣雞腿冷麵",
    "store": "7-11",
    "category": "lunch",
    "calories": 369,
    "protein_g": 23,
    "carbs_g": 42,
    "fat_g": 12,
    "price": 89,
    "photo_url": "https://www.7-11.com.tw/images/products/1.jpg",
    "description": "泰式酸辣雞腿冷麵：23g 蛋白質，369 kcal"
  },
  {
    "id": "7-11-lunch-2",
    "name": "京醬鴨絲飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 500,
    "protein_g": 31,
    "carbs_g": 56,
    "fat_g": 17,
    "price": 45,
    "photo_url": "https://www.7-11.com.tw/images/products/2.jpg",
    "description": "京醬鴨絲飯：31g 蛋白質，500 kcal"
  },
  {
    "id": "7-11-lunch-3",
    "name": "港式叉燒油雞飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 500,
    "protein_g": 31,
    "carbs_g": 56,
    "fat_g": 17,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/3.jpg",
    "description": "港式叉燒油雞飯：31g 蛋白質，500 kcal"
  },
  {
    "id": "7-11-lunch-4",
    "name": "三杯雞燴飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 700,
    "protein_g": 44,
    "carbs_g": 79,
    "fat_g": 23,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/4.jpg",
    "description": "三杯雞燴飯：44g 蛋白質，700 kcal"
  },
  {
    "id": "7-11-lunch-5",
    "name": "麻油雞飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 354,
    "protein_g": 22,
    "carbs_g": 40,
    "fat_g": 12,
    "price": 49,
    "photo_url": "https://www.7-11.com.tw/images/products/5.jpg",
    "description": "麻油雞飯：22g 蛋白質，354 kcal"
  },
  {
    "id": "7-11-lunch-6",
    "name": "四起司香草烤雞握便當",
    "store": "7-11",
    "category": "lunch",
    "calories": 414,
    "protein_g": 26,
    "carbs_g": 47,
    "fat_g": 14,
    "price": 69,
    "photo_url": "https://www.7-11.com.tw/images/products/6.jpg",
    "description": "四起司香草烤雞握便當：26g 蛋白質，414 kcal"
  },
  {
    "id": "7-11-lunch-7",
    "name": "爆蛋肉燥新極大飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 307,
    "protein_g": 23,
    "carbs_g": 32,
    "fat_g": 10,
    "price": 55,
    "photo_url": "https://www.7-11.com.tw/images/products/7.jpg",
    "description": "爆蛋肉燥新極大飯：23g 蛋白質，307 kcal"
  },
  {
    "id": "7-11-lunch-8",
    "name": "柱侯牛腱飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 574,
    "protein_g": 36,
    "carbs_g": 65,
    "fat_g": 19,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/8.jpg",
    "description": "柱侯牛腱飯：36g 蛋白質，574 kcal"
  },
  {
    "id": "7-11-lunch-9",
    "name": "府城肉燥厚切排骨飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 620,
    "protein_g": 39,
    "carbs_g": 70,
    "fat_g": 21,
    "price": 129,
    "photo_url": "https://www.7-11.com.tw/images/products/9.jpg",
    "description": "府城肉燥厚切排骨飯：39g 蛋白質，620 kcal"
  },
  {
    "id": "7-11-lunch-10",
    "name": "米香鹹酥蝦飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 226,
    "protein_g": 16,
    "carbs_g": 24,
    "fat_g": 7,
    "price": 49,
    "photo_url": "https://www.7-11.com.tw/images/products/10.jpg",
    "description": "米香鹹酥蝦飯：16g 蛋白質，226 kcal"
  },
  {
    "id": "7-11-lunch-11",
    "name": "晶英三杯蛤蜊飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 250,
    "protein_g": 18,
    "carbs_g": 27,
    "fat_g": 8,
    "price": 39,
    "photo_url": "https://www.7-11.com.tw/images/products/11.jpg",
    "description": "晶英三杯蛤蜊飯：18g 蛋白質，250 kcal"
  },
  {
    "id": "7-11-lunch-12",
    "name": "晶英韓式炸豬排起司雙拼飯",
    "store": "7-11",
    "category": "lunch",
    "calories": 351,
    "protein_g": 22,
    "carbs_g": 39,
    "fat_g": 12,
    "price": 89,
    "photo_url": "https://www.7-11.com.tw/images/products/12.jpg",
    "description": "晶英韓式炸豬排起司雙拼飯：22g 蛋白質，351 kcal"
  },
  {
    "id": "7-11-lunch-13",
    "name": "麻辣奶油鮮蝦義大利麵",
    "store": "7-11",
    "category": "lunch",
    "calories": 586,
    "protein_g": 41,
    "carbs_g": 63,
    "fat_g": 19,
    "price": 149,
    "photo_url": "https://www.7-11.com.tw/images/products/13.jpg",
    "description": "麻辣奶油鮮蝦義大利麵：41g 蛋白質，586 kcal"
  },
  {
    "id": "7-11-breakfast-14",
    "name": "御飯糰-梅子紫蘇",
    "store": "7-11",
    "category": "breakfast",
    "calories": 180,
    "protein_g": 7,
    "carbs_g": 23,
    "fat_g": 7,
    "price": 25,
    "photo_url": "https://www.7-11.com.tw/images/products/14.jpg",
    "description": "御飯糰-梅子紫蘇：7g 蛋白質，180 kcal"
  },
  {
    "id": "7-11-breakfast-15",
    "name": "御飯糰-鮭魚",
    "store": "7-11",
    "category": "breakfast",
    "calories": 190,
    "protein_g": 13,
    "carbs_g": 21,
    "fat_g": 6,
    "price": 28,
    "photo_url": "https://www.7-11.com.tw/images/products/15.jpg",
    "description": "御飯糰-鮭魚：13g 蛋白質，190 kcal"
  },
  {
    "id": "7-11-breakfast-16",
    "name": "御飯糰-鮪魚起司",
    "store": "7-11",
    "category": "breakfast",
    "calories": 200,
    "protein_g": 14,
    "carbs_g": 22,
    "fat_g": 6,
    "price": 30,
    "photo_url": "https://www.7-11.com.tw/images/products/16.jpg",
    "description": "御飯糰-鮪魚起司：14g 蛋白質，200 kcal"
  },
  {
    "id": "7-11-breakfast-17",
    "name": "原賞三明治-火腿起司蛋",
    "store": "7-11",
    "category": "breakfast",
    "calories": 280,
    "protein_g": 21,
    "carbs_g": 29,
    "fat_g": 9,
    "price": 45,
    "photo_url": "https://www.7-11.com.tw/images/products/17.jpg",
    "description": "原賞三明治-火腿起司蛋：21g 蛋白質，280 kcal"
  },
  {
    "id": "7-11-breakfast-18",
    "name": "原賞三明治-雞肉沙拉",
    "store": "7-11",
    "category": "breakfast",
    "calories": 240,
    "protein_g": 15,
    "carbs_g": 27,
    "fat_g": 8,
    "price": 48,
    "photo_url": "https://www.7-11.com.tw/images/products/18.jpg",
    "description": "原賞三明治-雞肉沙拉：15g 蛋白質，240 kcal"
  },
  {
    "id": "7-11-breakfast-19",
    "name": "7-11茶葉蛋",
    "store": "7-11",
    "category": "breakfast",
    "calories": 50,
    "protein_g": 4,
    "carbs_g": 5,
    "fat_g": 2,
    "price": 10,
    "photo_url": "https://www.7-11.com.tw/images/products/19.jpg",
    "description": "7-11茶葉蛋：4g 蛋白質，50 kcal"
  },
  {
    "id": "7-11-breakfast-20",
    "name": "豆漿早餐組合",
    "store": "7-11",
    "category": "breakfast",
    "calories": 300,
    "protein_g": 15,
    "carbs_g": 36,
    "fat_g": 11,
    "price": 35,
    "photo_url": "https://www.7-11.com.tw/images/products/20.jpg",
    "description": "豆漿早餐組合：15g 蛋白質，300 kcal"
  },
  {
    "id": "7-11-dinner-21",
    "name": "台韓半半炸雞便當",
    "store": "7-11",
    "category": "dinner",
    "calories": 650,
    "protein_g": 41,
    "carbs_g": 73,
    "fat_g": 22,
    "price": 119,
    "photo_url": "https://www.7-11.com.tw/images/products/21.jpg",
    "description": "台韓半半炸雞便當：41g 蛋白質，650 kcal"
  },
  {
    "id": "7-11-dinner-22",
    "name": "泡菜豬肉豆腐煲燴飯",
    "store": "7-11",
    "category": "dinner",
    "calories": 531,
    "protein_g": 33,
    "carbs_g": 60,
    "fat_g": 18,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/22.jpg",
    "description": "泡菜豬肉豆腐煲燴飯：33g 蛋白質，531 kcal"
  },
  {
    "id": "7-11-dinner-23",
    "name": "椰香綠咖哩嫩雞飯",
    "store": "7-11",
    "category": "dinner",
    "calories": 668,
    "protein_g": 42,
    "carbs_g": 75,
    "fat_g": 22,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/23.jpg",
    "description": "椰香綠咖哩嫩雞飯：42g 蛋白質，668 kcal"
  },
  {
    "id": "7-11-dinner-24",
    "name": "港式醬燜牛肉燴飯",
    "store": "7-11",
    "category": "dinner",
    "calories": 488,
    "protein_g": 31,
    "carbs_g": 55,
    "fat_g": 16,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/24.jpg",
    "description": "港式醬燜牛肉燴飯：31g 蛋白質，488 kcal"
  },
  {
    "id": "family-lunch-1",
    "name": "泰式酸辣雞腿冷麵",
    "store": "全家",
    "category": "lunch",
    "calories": 369,
    "protein_g": 23,
    "carbs_g": 42,
    "fat_g": 12,
    "price": 89,
    "photo_url": "https://www.7-11.com.tw/images/products/1.jpg",
    "description": "泰式酸辣雞腿冷麵：23g 蛋白質，369 kcal"
  },
  {
    "id": "family-lunch-2",
    "name": "京醬鴨絲飯",
    "store": "全家",
    "category": "lunch",
    "calories": 500,
    "protein_g": 31,
    "carbs_g": 56,
    "fat_g": 17,
    "price": 45,
    "photo_url": "https://www.7-11.com.tw/images/products/2.jpg",
    "description": "京醬鴨絲飯：31g 蛋白質，500 kcal"
  },
  {
    "id": "family-lunch-3",
    "name": "港式叉燒油雞飯",
    "store": "全家",
    "category": "lunch",
    "calories": 500,
    "protein_g": 31,
    "carbs_g": 56,
    "fat_g": 17,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/3.jpg",
    "description": "港式叉燒油雞飯：31g 蛋白質，500 kcal"
  },
  {
    "id": "family-lunch-4",
    "name": "三杯雞燴飯",
    "store": "全家",
    "category": "lunch",
    "calories": 700,
    "protein_g": 44,
    "carbs_g": 79,
    "fat_g": 23,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/4.jpg",
    "description": "三杯雞燴飯：44g 蛋白質，700 kcal"
  },
  {
    "id": "family-lunch-5",
    "name": "麻油雞飯",
    "store": "全家",
    "category": "lunch",
    "calories": 354,
    "protein_g": 22,
    "carbs_g": 40,
    "fat_g": 12,
    "price": 49,
    "photo_url": "https://www.7-11.com.tw/images/products/5.jpg",
    "description": "麻油雞飯：22g 蛋白質，354 kcal"
  },
  {
    "id": "family-lunch-6",
    "name": "四起司香草烤雞握便當",
    "store": "全家",
    "category": "lunch",
    "calories": 414,
    "protein_g": 26,
    "carbs_g": 47,
    "fat_g": 14,
    "price": 69,
    "photo_url": "https://www.7-11.com.tw/images/products/6.jpg",
    "description": "四起司香草烤雞握便當：26g 蛋白質，414 kcal"
  },
  {
    "id": "family-lunch-7",
    "name": "爆蛋肉燥新極大飯",
    "store": "全家",
    "category": "lunch",
    "calories": 307,
    "protein_g": 23,
    "carbs_g": 32,
    "fat_g": 10,
    "price": 55,
    "photo_url": "https://www.7-11.com.tw/images/products/7.jpg",
    "description": "爆蛋肉燥新極大飯：23g 蛋白質，307 kcal"
  },
  {
    "id": "family-lunch-8",
    "name": "柱侯牛腱飯",
    "store": "全家",
    "category": "lunch",
    "calories": 574,
    "protein_g": 36,
    "carbs_g": 65,
    "fat_g": 19,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/8.jpg",
    "description": "柱侯牛腱飯：36g 蛋白質，574 kcal"
  },
  {
    "id": "family-lunch-9",
    "name": "府城肉燥厚切排骨飯",
    "store": "全家",
    "category": "lunch",
    "calories": 620,
    "protein_g": 39,
    "carbs_g": 70,
    "fat_g": 21,
    "price": 129,
    "photo_url": "https://www.7-11.com.tw/images/products/9.jpg",
    "description": "府城肉燥厚切排骨飯：39g 蛋白質，620 kcal"
  },
  {
    "id": "family-lunch-10",
    "name": "米香鹹酥蝦飯",
    "store": "全家",
    "category": "lunch",
    "calories": 226,
    "protein_g": 16,
    "carbs_g": 24,
    "fat_g": 7,
    "price": 49,
    "photo_url": "https://www.7-11.com.tw/images/products/10.jpg",
    "description": "米香鹹酥蝦飯：16g 蛋白質，226 kcal"
  },
  {
    "id": "family-lunch-11",
    "name": "晶英三杯蛤蜊飯",
    "store": "全家",
    "category": "lunch",
    "calories": 250,
    "protein_g": 18,
    "carbs_g": 27,
    "fat_g": 8,
    "price": 39,
    "photo_url": "https://www.7-11.com.tw/images/products/11.jpg",
    "description": "晶英三杯蛤蜊飯：18g 蛋白質，250 kcal"
  },
  {
    "id": "family-lunch-12",
    "name": "晶英韓式炸豬排起司雙拼飯",
    "store": "全家",
    "category": "lunch",
    "calories": 351,
    "protein_g": 22,
    "carbs_g": 39,
    "fat_g": 12,
    "price": 89,
    "photo_url": "https://www.7-11.com.tw/images/products/12.jpg",
    "description": "晶英韓式炸豬排起司雙拼飯：22g 蛋白質，351 kcal"
  },
  {
    "id": "family-lunch-13",
    "name": "麻辣奶油鮮蝦義大利麵",
    "store": "全家",
    "category": "lunch",
    "calories": 586,
    "protein_g": 41,
    "carbs_g": 63,
    "fat_g": 19,
    "price": 149,
    "photo_url": "https://www.7-11.com.tw/images/products/13.jpg",
    "description": "麻辣奶油鮮蝦義大利麵：41g 蛋白質，586 kcal"
  },
  {
    "id": "family-breakfast-14",
    "name": "御飯糰-梅子紫蘇",
    "store": "全家",
    "category": "breakfast",
    "calories": 180,
    "protein_g": 7,
    "carbs_g": 23,
    "fat_g": 7,
    "price": 25,
    "photo_url": "https://www.7-11.com.tw/images/products/14.jpg",
    "description": "御飯糰-梅子紫蘇：7g 蛋白質，180 kcal"
  },
  {
    "id": "family-breakfast-15",
    "name": "御飯糰-鮭魚",
    "store": "全家",
    "category": "breakfast",
    "calories": 190,
    "protein_g": 13,
    "carbs_g": 21,
    "fat_g": 6,
    "price": 28,
    "photo_url": "https://www.7-11.com.tw/images/products/15.jpg",
    "description": "御飯糰-鮭魚：13g 蛋白質，190 kcal"
  },
  {
    "id": "family-breakfast-16",
    "name": "御飯糰-鮪魚起司",
    "store": "全家",
    "category": "breakfast",
    "calories": 200,
    "protein_g": 14,
    "carbs_g": 22,
    "fat_g": 6,
    "price": 30,
    "photo_url": "https://www.7-11.com.tw/images/products/16.jpg",
    "description": "御飯糰-鮪魚起司：14g 蛋白質，200 kcal"
  },
  {
    "id": "family-breakfast-17",
    "name": "原賞三明治-火腿起司蛋",
    "store": "全家",
    "category": "breakfast",
    "calories": 280,
    "protein_g": 21,
    "carbs_g": 29,
    "fat_g": 9,
    "price": 45,
    "photo_url": "https://www.7-11.com.tw/images/products/17.jpg",
    "description": "原賞三明治-火腿起司蛋：21g 蛋白質，280 kcal"
  },
  {
    "id": "family-breakfast-18",
    "name": "原賞三明治-雞肉沙拉",
    "store": "全家",
    "category": "breakfast",
    "calories": 240,
    "protein_g": 15,
    "carbs_g": 27,
    "fat_g": 8,
    "price": 48,
    "photo_url": "https://www.7-11.com.tw/images/products/18.jpg",
    "description": "原賞三明治-雞肉沙拉：15g 蛋白質，240 kcal"
  },
  {
    "id": "family-breakfast-19",
    "name": "7-11茶葉蛋",
    "store": "全家",
    "category": "breakfast",
    "calories": 50,
    "protein_g": 4,
    "carbs_g": 5,
    "fat_g": 2,
    "price": 10,
    "photo_url": "https://www.7-11.com.tw/images/products/19.jpg",
    "description": "7-11茶葉蛋：4g 蛋白質，50 kcal"
  },
  {
    "id": "family-breakfast-20",
    "name": "豆漿早餐組合",
    "store": "全家",
    "category": "breakfast",
    "calories": 300,
    "protein_g": 15,
    "carbs_g": 36,
    "fat_g": 11,
    "price": 35,
    "photo_url": "https://www.7-11.com.tw/images/products/20.jpg",
    "description": "豆漿早餐組合：15g 蛋白質，300 kcal"
  },
  {
    "id": "family-dinner-21",
    "name": "台韓半半炸雞便當",
    "store": "全家",
    "category": "dinner",
    "calories": 650,
    "protein_g": 41,
    "carbs_g": 73,
    "fat_g": 22,
    "price": 119,
    "photo_url": "https://www.7-11.com.tw/images/products/21.jpg",
    "description": "台韓半半炸雞便當：41g 蛋白質，650 kcal"
  },
  {
    "id": "family-dinner-22",
    "name": "泡菜豬肉豆腐煲燴飯",
    "store": "全家",
    "category": "dinner",
    "calories": 531,
    "protein_g": 33,
    "carbs_g": 60,
    "fat_g": 18,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/22.jpg",
    "description": "泡菜豬肉豆腐煲燴飯：33g 蛋白質，531 kcal"
  },
  {
    "id": "family-dinner-23",
    "name": "椰香綠咖哩嫩雞飯",
    "store": "全家",
    "category": "dinner",
    "calories": 668,
    "protein_g": 42,
    "carbs_g": 75,
    "fat_g": 22,
    "price": 99,
    "photo_url": "https://www.7-11.com.tw/images/products/23.jpg",
    "description": "椰香綠咖哩嫩雞飯：42g 蛋白質，668 kcal"
  },
  {
    "id": "family-dinner-24",
    "name": "港式醬燜牛肉燴飯",
    "store": "全家",
    "category": "dinner",
    "calories": 488,
    "protein_g": 31,
    "carbs_g": 55,
    "fat_g": 16,
    "price": 109,
    "photo_url": "https://www.7-11.com.tw/images/products/24.jpg",
    "description": "港式醬燜牛肉燴飯：31g 蛋白質，488 kcal"
  }
]

export function getConvenienceItems(category: 'breakfast' | 'lunch' | 'dinner'): ConvenienceItem[] {
  return convenienceStoreMenu.filter(item => item.category === category)
}

export function getConvenienceItemsByStore(store: '7-11' | '全家', category: 'breakfast' | 'lunch' | 'dinner'): ConvenienceItem[] {
  return convenienceStoreMenu.filter(item => item.store === store && item.category === category)
}
