/** BetterBit icon semantic names — single registry */
export type BBIconName =
  | 'calories'
  | 'protein'
  | 'carbs'
  | 'fat'
  | 'water'
  | 'workout'
  | 'cardio'
  | 'sleep'
  | 'weight'
  | 'progress'
  | 'target'
  | 'best'
  | 'needImprove'
  | 'meal'
  | 'breakfast'
  | 'lunch'
  | 'dinner'
  | 'snack'
  | 'neat'
  | 'rest'
  | 'recommendation'
  | 'ai'
  | 'analysis'
  | 'challenge'
  | 'calendar'
  | 'weekScore'
  | 'success'
  | 'warning'
  | 'error'
  | 'neutral'

export type BBIconTone = 'default' | 'accent' | 'success' | 'warning' | 'danger' | 'muted' | 'water'

export type BBScoreSignal = 'green' | 'yellow' | 'red' | 'neutral'

export type DietScoreSignal = 'green' | 'yellow' | 'red'
